apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-second-app-deployment
  labels:
    app: my-second-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-second-app
  template:
    metadata:
      labels:
        app: my-second-app
    spec:
      containers:
      - name: my-second-app
        image: nathancastelein/vuejs-app:latest
        ports:
        - containerPort: 8080